In [4]:
import pandas as pd
import numpy as np

Exercise 2 - Filtering
Return the following subsets of the dataframe.

How many listings are there with a price less than 100?
Find how many listings there are in just Brooklyn.
Find how many listings there are in Brooklyn with a price less than 100.
Using .isin() select anyone that has the host name of Michael, David, John, and Daniel.
Count the amout of names each time appears.
Create a new column called adjusted_price that has $100 added to every listing in Williamsburg. The prices for all other listings should be the same as the were before.
What % of the rooms are private, and what % of the rooms are shared.
Hint, use .value_counts()
Challenge:

Listings with the word brownstone in the name (hint to come, might move this one later if needed)
hint... build a function to check for 'brownstone' and apply that function OR df.name.str.????

## How many listings are ther with a price less than 100?

In [10]:
df = pd.read_csv("listings.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

In [23]:
condition = df['price'] < 100
df[condition].head()
df[condition]['id'].count()

22778

## How many listings are there in Brooklyn?

In [30]:
df_bk = pd.read_csv("listings.csv")

condition2 = df_bk['neighbourhood_group'] == 'Brooklyn'
df_bk[condition2].head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0

In [31]:
df_bk[condition2]['neighbourhood_group'].count()

18632

## Find how many listings there are in Brooklyn with a price less than 100

In [27]:
condition2 = df['neighbourhood_group'] == 'Brooklyn'
condition = df['price'] < 100

df[condition & condition2]['id'].count()

10473

## Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.##

In [35]:
host_name = ['Michael', 'David', 'John', 'Daniel']

condition = df.host_name.isin(host_name)

df[condition].head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
52,16595,LOFT HAVEN ~ Six Windows ~ Bricks ~ Plants ~ Q...,64522,Daniel,Brooklyn,Williamsburg,40.70933,-73.96792,Entire home/apt,271,1,172,2020-07-14,1.44,1,365
201,61747,"Cozy, Brooklyn, Prospect Park Studio",299370,David,Brooklyn,Prospect-Lefferts Gardens,40.65979,-73.96180,Entire home/apt,91,14,97,2018-01-31,0.83,1,44
209,62903,Beautiful modern studio apartment in heart of NYC,306605,Daniel,Manhattan,Chelsea,40.74238,-73.99567,Entire home/apt,205,15,68,2019-12-14,0.67,2,89
220,64015,Prime East Village 1 Bedroom,146944,David,Manhattan,East Village,40.72807,-73.98594,Entire home/apt,200,3,0,NaN,NaN,1,0
260,74073,Food & Music Dream Apartment in Williamsburg,211877,Daniel,Brooklyn,Williamsburg,40.71113,-73.96054,Entire home/apt,187,30,90,2020-07-31,0.81,1,261

## 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg. The prices for all other listings should be the same as the were before

In [57]:
df['adjusted_price'] = np.where(c1, df['price'] + 100, df['price'])
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,is_in_williamsburg,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,0,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,0,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,0,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,0,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,0,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164,0,145
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85,0,87
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90,0,59
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113,0,80
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50â€™ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38,0,66

## 6. What % of the rooms are private, and what % of the rooms are shared.

In [77]:
c2 = df['room_type'] == 'Private room'

df[c2]['room_type'].count()/df['room_type'].count() *100

45.444580566122895

In [85]:
c3 = df['room_type'] == 'Shared room'

df[c3]['room_type'].count()/df['room_type'].count() *100

2.12134889419047